[tool.poetry]
name = "video-processing"
version = "0.1.0"
description = ""
authors = ["skyler arnold <skyarnold1@me.com>"]
readme = "README.md"
packages = [{include = "video_processing"}]

[tool.poetry.dependencies]
python = ">=3.10, <4.0"
scipy = "^1.9.3"
numpy = "^1.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
